[package]
name = "rust-maze-dfs-solver"
version = "0.1.0"
authors = ["Neuton Foo <neuton.foo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
